### ISSUE TITLE
Exception: List of measurements in "UI thread" series is empty

### ISSUE THREAD

**Issue by spauldhaliwal** [filiph/benchmarkhor#1]
When running benchextract timeline.json, I get `Exception: List of measurements in "UI thread" series is empty`

Furthermore, after searching through the generated timeline.json that `driver.stopTracingAndDownloadTimeline()` provides, I find no instances of "MessageLoop::FlushTasks", which seems to be the message benchmarkhor is looking for in order to measure ui events. As this hasn't been updated in a couple of years, I'm wondering if the flutter team has renamed the above label and that's why the tool can't find any measurements on the ui thread.

Or am I doing something wrong when generating my timeline.json? My flutter_driver test is about 60 seconds long and slowly scrolls through a list of items on screen, the resulting timeline.json is ~6mb. Does that seem normal?

**Comment by filiph** [comment]
You are most probably correct. The `MessageLoop::FlushTasks` was probably renamed to something else. I'm in no state to fix this anytime soon, though. Sorry about that!

**Comment by filiph** [comment]
I have marked the package on pub.dev as DISCONTINUED to dissuade people from using it. It's not that the package will never be touched again — I hope to use it at some point in the future. But I'd hate to mislead people into thinking it's working when it's not.

Thanks again for the report!

**Comment by LeonManolo** [comment]
> You are most probably correct. The `MessageLoop::FlushTasks` was probably renamed to something else. I'm in no state to fix this anytime soon, though. Sorry about that!

Hello Filip,

I recently encountered the same issue as @spauldhaliwal, I've noticed the absence of the "MessageLoop::FlushTasks" event in the timeline.json generated by driver.stopTracingAndDownloadTimeline().

In your response, you mentioned that "MessageLoop::FlushTasks" was probably renamed, which might explain why the tool fails to find any UI thread measurements.

While following your article on performance testing in Flutter ([Performance testing of Flutter apps](https://medium.com/flutter/performance-testing-of-flutter-apps-df7669bb7df7)), I attempted to replicate the analysis and visualized my timeline.json in Chrome. However, I noticed a difference between the [graphical representation of the timeline JSON in your article](https://miro.medium.com/v2/resize:fit:720/format:webp/1*Y7-lpotj3tTjqJyobYyKHw.png) and what I observed in my data. Specifically, in your article, "MessageLoop::FlushTasks" appears clearly above "Rasterizer::DoDraw", while in my visualization, there's nothing listed above "Rasterizer::DoDraw". I've attached an image of my timeline visualization for reference.
![Screenshot 2024-02-29 at 18 43 03](https://github.com/filiph/benchmarkhor/assets/87019114/d716578f-32e8-472e-a3e1-c2a31da2c7c2)


Given your expertise and understanding of Flutter's performance testing, do you have any insights or suggestions on how to address this issue? I'm particularly interested in resources or documentation that might help identify the current equivalent of the "MessageLoop::FlushTasks" event. Any strategies for capturing relevant performance metrics, in the absence of this event, would also be highly valuable.

I understand the constraints on your time and resources, so any guidance or even a nudge in the right direction would be immensely appreciated.

Thank you very much for your time.

Best regards,
Leon-Manolo

**Comment by filiph** [comment]
Hi Leon-Manolo,

I'm guessing the only solution is to look at the current timelines generated by Flutter and find all the things that are currently top-level (what used to be just `MessageLoop::FlushTasks`). This might mean rewriting https://github.com/filiph/benchmarkhor/blob/498375cb4d8aca6340018c0a2750c2a4d2e346ba/lib/extract.dart#L28-L32 so that it combines several top-level events.

**Comment by spauldhaliwal** [comment]
@filiph The package is still marked as discontinued, but I went ahead and gave your latest changes a try. It did not work, and I believe the reason is as follows:

On the latest stable flutter version 3.2.4, my UI thread is identified by `1.ui...` and my raster thread is identified by `1.raster...`

UI:
```
    {
      "name": "thread_name",
      "ph": "M",
      "pid": 7139,
      "tid": 7184,
      "args": {
        "name": "1.ui (7184)",
        "mode": "basic"
      }
    },
```

Raster:
```
    {
      "name": "thread_name",
      "ph": "M",
      "pid": 7139,
      "tid": 7185,
      "args": {
        "name": "1.raster (7185)",
        "mode": "basic"
      }
    },
```

The naming scheme for the UI times and Raster times matches the above commit, however:

UI time:
```
    {
      "name": "Dart_InvokeClosure",
      "cat": "API",
      "tid": 7184,
      "pid": 7139,
      "ts": 39056917914,
      "ph": "E",
      "args": {
        "isolateId": "isolates/6617659661331463",
        "isolateGroupId": "isolateGroups/4915563461788185"
      }
    },
```

Raster time
```
    {
      "name": "GPURasterizer::Draw",
      "cat": "Embedder",
      "tid": 7185,
      "pid": 7139,
      "ts": 39056942201,
      "ph": "E",
      "args": {}
    },
```

**Edit:** Tested on Android only and tested with and without --enable-impeller. Results were the same.

**Edit 2:** Tested locally by renaming back to 1.ui and 1.raster and it seems to be working correctly.

**Comment by filiph** [comment]
Thanks for looking into it. I think the names of the threads depend on the operating system, too. I'm thinking of just using `TimelineSummary` instead of the raw timeline. It'll prevent me from doing some of the fancier benchmarks I had in mind, but YAGNI. I can always go back to the raw Timeline later.
